import React from 'react';

const HomePage = () => {
    const tekst = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pulvinar est lacus, ullamcorper sollicitudin leo porta id. Donec vestibulum leo a ipsum dapibus, at lobortis dolor maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In vestibulum lorem porttitor nisl rutrum, eu pellentesque diam aliquam. Curabitur euismod vitae erat eget suscipit. Mauris porta mattis libero, at hendrerit felis aliquet eu. Fusce porttitor ullamcorper purus, sed vulputate quam tincidunt sed. Nunc eget consequat orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc ac pulvinar nibh.

    Fusce vestibulum elit tortor, ut posuere lectus feugiat iaculis. Vivamus cursus nec augue in rutrum. Mauris eros orci, tristique ut iaculis tincidunt, mollis aliquet lorem. Morbi hendrerit libero ac ex sagittis euismod ac at tellus. Fusce venenatis efficitur orci, interdum congue magna viverra nec. Morbi enim nibh, iaculis in porta ac, sollicitudin in justo. Phasellus lorem nunc, vulputate quis enim non, dictum porta massa. Cras eu varius tellus, sed feugiat libero. Nam in ligula at arcu venenatis egestas a a elit.
    
    Nam sit amet ante eu eros hendrerit ultricies. Suspendisse tempus, tellus id aliquet accumsan, sapien nulla mattis lacus, ut posuere orci metus sagittis lacus. Phasellus eget quam ornare, eleifend justo non, pulvinar sem. Integer mollis molestie dictum. Fusce vel ligula ut mauris posuere venenatis. Suspendisse ac risus tellus. Integer volutpat ipsum vel diam congue, sit amet feugiat mi tempus. Vestibulum blandit magna eget eros tincidunt, quis condimentum sem egestas. Nunc est augue, tincidunt sit amet interdum imperdiet, imperdiet nec sapien. Nunc commodo, est a ornare tempor, nisl orci pellentesque est, eu commodo ante risus consequat leo. Vivamus lobortis cursus congue. Donec commodo lobortis orci sit amet tincidunt. Donec ac nisi pellentesque metus porttitor posuere.
    
    Duis a rutrum magna, vel pharetra quam. Etiam mattis nisi a felis efficitur vulputate. Fusce tempus, nulla eu hendrerit ultrices, quam quam iaculis risus, eget rutrum tellus leo ut libero. Nulla at lorem ornare, mollis nisi vitae, tristique augue. Aenean efficitur massa eu dolor sollicitudin efficitur. Praesent ac arcu arcu. Sed interdum efficitur tellus, sed faucibus sapien viverra finibus. Vivamus quis dui laoreet, pulvinar lectus et, interdum odio. Duis bibendum leo est. Maecenas nec leo eget lectus auctor auctor. Nunc pellentesque lorem sed neque facilisis, eu malesuada enim accumsan. Donec feugiat magna non ipsum facilisis rutrum.
    
    In mi urna, scelerisque non mauris non, aliquet mollis tellus. Curabitur consectetur arcu ut turpis semper mattis. Aliquam blandit tellus odio, eget pulvinar eros consectetur quis. Etiam luctus tortor sed velit blandit dapibus. Ut dolor sapien, gravida in dictum nec, rutrum ac eros. Vestibulum id tellus in erat scelerisque consequat. Mauris egestas sagittis vehicula. Duis consectetur dolor non diam condimentum fermentum ac ut arcu.`;
    
    return <div className="p-l">{tekst}{tekst}{tekst}{tekst}</div>
}

export default HomePage;